<?php
namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $region = [
            ['id' => 'AF', 'name' => 'Afghanistan', 'continent' => 'Asia'],
            ['id' => 'AX', 'name' => 'Åland Islands', 'continent' => 'Europe'],
            ['id' => 'AL', 'name' => 'Albania', 'continent' => 'Europe'],
            ['id' => 'DZ', 'name' => 'Algeria', 'continent' => 'Africa'],
            ['id' => 'AS', 'name' => 'American Samoa', 'continent' => 'Australia (Oceania)'],
            ['id' => 'AD', 'name' => 'Andorra', 'continent' => 'Europe'],
            ['id' => 'AO', 'name' => 'Angola', 'continent' => 'Africa'],
            ['id' => 'AI', 'name' => 'Anguilla', 'continent' => 'North America'],
            ['id' => 'AQ', 'name' => 'Antarctica', 'continent' => 'Antarctica'],
            ['id' => 'AG', 'name' => 'Antigua and Barbuda', 'continent' => 'North America'],
            ['id' => 'AR', 'name' => 'Argentina', 'continent' => 'South America'],
            ['id' => 'AM', 'name' => 'Armenia', 'continent' => 'Asia'],
            ['id' => 'AW', 'name' => 'Aruba', 'continent' => 'North America'],
            ['id' => 'AU', 'name' => 'Australia', 'continent' => 'Australia (Oceania)'],
            ['id' => 'AT', 'name' => 'Austria', 'continent' => 'Europe'],
            ['id' => 'AZ', 'name' => 'Azerbaijan', 'continent' => 'Asia'],
            ['id' => 'BS', 'name' => 'Bahamas', 'continent' => 'North America'],
            ['id' => 'BH', 'name' => 'Bahrain', 'continent' => 'Asia'],
            ['id' => 'BD', 'name' => 'Bangladesh', 'continent' => 'Asia'],
            ['id' => 'BB', 'name' => 'Barbados', 'continent' => 'North America'],
            ['id' => 'BY', 'name' => 'Belarus', 'continent' => 'Europe'],
            ['id' => 'BE', 'name' => 'Belgium', 'continent' => 'Europe'],
            ['id' => 'BZ', 'name' => 'Belize', 'continent' => 'North America'],
            ['id' => 'BJ', 'name' => 'Benin', 'continent' => 'Africa'],
            ['id' => 'BM', 'name' => 'Bermuda', 'continent' => 'North America'],
            ['id' => 'BT', 'name' => 'Bhutan', 'continent' => 'Asia'],
            ['id' => 'BO', 'name' => 'Bolivia (Plurinational State of)', 'continent' => 'South America'],
            ['id' => 'BA', 'name' => 'Bosnia and Herzegovina', 'continent' => 'Europe'],
            ['id' => 'BW', 'name' => 'Botswana', 'continent' => 'Africa'],
            ['id' => 'BV', 'name' => 'Bouvet Island', 'continent' => 'Antarctica'],
            ['id' => 'BR', 'name' => 'Brazil', 'continent' => 'South America'],
            ['id' => 'IO', 'name' => 'British Indian Ocean Territory', 'continent' => 'Asia'],
            ['id' => 'BN', 'name' => 'Brunei Darussalam', 'continent' => 'Asia'],
            ['id' => 'BG', 'name' => 'Bulgaria', 'continent' => 'Europe'],
            ['id' => 'BF', 'name' => 'Burkina Faso', 'continent' => 'Africa'],
            ['id' => 'BI', 'name' => 'Burundi', 'continent' => 'Africa'],
            ['id' => 'CV', 'name' => 'Cabo Verde', 'continent' => 'Africa'],
            ['id' => 'KH', 'name' => 'Cambodia', 'continent' => 'Asia'],
            ['id' => 'CM', 'name' => 'Cameroon', 'continent' => 'Africa'],
            ['id' => 'CA', 'name' => 'Canada', 'continent' => 'North America'],
            ['id' => 'BQ', 'name' => 'Caribbean Netherlands', 'continent' => 'North America'],
            ['id' => 'KY', 'name' => 'Cayman Islands', 'continent' => 'North America'],
            ['id' => 'CF', 'name' => 'Central African Republic', 'continent' => 'Africa'],
            ['id' => 'TD', 'name' => 'Chad', 'continent' => 'Africa'],
            ['id' => 'CL', 'name' => 'Chile', 'continent' => 'South America'],
            ['id' => 'CN', 'name' => 'China', 'continent' => 'Asia'],
            ['id' => 'CX', 'name' => 'Christmas Island', 'continent' => 'Asia'],
            ['id' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'continent' => 'Asia'],
            ['id' => 'CO', 'name' => 'Colombia', 'continent' => 'South America'],
            ['id' => 'KM', 'name' => 'Comoros', 'continent' => 'Africa'],
            ['id' => 'CG', 'name' => 'Congo', 'continent' => 'Africa'],
            ['id' => 'CD', 'name' => 'Congo, Democratic Republic of the', 'continent' => 'Africa'],
            ['id' => 'CK', 'name' => 'Cook Islands', 'continent' => 'Australia (Oceania)'],
            ['id' => 'CR', 'name' => 'Costa Rica', 'continent' => 'North America'],
            ['id' => 'HR', 'name' => 'Croatia', 'continent' => 'Europe'],
            ['id' => 'CU', 'name' => 'Cuba', 'continent' => 'North America'],
            ['id' => 'CW', 'name' => 'Curaçao', 'continent' => 'North America'],
            ['id' => 'CY', 'name' => 'Cyprus', 'continent' => 'Asia'],
            ['id' => 'CZ', 'name' => 'Czech Republic', 'continent' => 'Europe'],
            ['id' => 'CI', 'name' => 'Côte d\'Ivoire', 'continent' => 'Africa'],
            ['id' => 'DK', 'name' => 'Denmark', 'continent' => 'Europe'],
            ['id' => 'DJ', 'name' => 'Djibouti', 'continent' => 'Africa'],
            ['id' => 'DM', 'name' => 'Dominica', 'continent' => 'North America'],
            ['id' => 'DO', 'name' => 'Dominican Republic', 'continent' => 'North America'],
            ['id' => 'EC', 'name' => 'Ecuador', 'continent' => 'South America'],
            ['id' => 'EG', 'name' => 'Egypt', 'continent' => 'Africa'],
            ['id' => 'SV', 'name' => 'El Salvador', 'continent' => 'North America'],
            ['id' => 'GQ', 'name' => 'Equatorial Guinea', 'continent' => 'Africa'],
            ['id' => 'ER', 'name' => 'Eritrea', 'continent' => 'Africa'],
            ['id' => 'EE', 'name' => 'Estonia', 'continent' => 'Europe'],
            ['id' => 'SZ', 'name' => 'Eswatini (Swaziland)', 'continent' => 'Africa'],
            ['id' => 'ET', 'name' => 'Ethiopia', 'continent' => 'Africa'],
            ['id' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'continent' => 'South America'],
            ['id' => 'FO', 'name' => 'Faroe Islands', 'continent' => 'Europe'],
            ['id' => 'FJ', 'name' => 'Fiji', 'continent' => 'Australia (Oceania)'],
            ['id' => 'FI', 'name' => 'Finland', 'continent' => 'Europe'],
            ['id' => 'FR', 'name' => 'France', 'continent' => 'Europe'],
            ['id' => 'GF', 'name' => 'French Guiana', 'continent' => 'South America'],
            ['id' => 'PF', 'name' => 'French Polynesia', 'continent' => 'Australia (Oceania)'],
            ['id' => 'TF', 'name' => 'French Southern Territories', 'continent' => 'Antarctica'],
            ['id' => 'GA', 'name' => 'Gabon', 'continent' => 'Africa'],
            ['id' => 'GM', 'name' => 'Gambia', 'continent' => 'Africa'],
            ['id' => 'GE', 'name' => 'Georgia', 'continent' => 'Asia'],
            ['id' => 'DE', 'name' => 'Germany', 'continent' => 'Europe'],
            ['id' => 'GH', 'name' => 'Ghana', 'continent' => 'Africa'],
            ['id' => 'GI', 'name' => 'Gibraltar', 'continent' => 'Europe'],
            ['id' => 'GR', 'name' => 'Greece', 'continent' => 'Europe'],
            ['id' => 'GL', 'name' => 'Greenland', 'continent' => 'North America'],
            ['id' => 'GD', 'name' => 'Grenada', 'continent' => 'North America'],
            ['id' => 'GP', 'name' => 'Guadeloupe', 'continent' => 'North America'],
            ['id' => 'GU', 'name' => 'Guam', 'continent' => 'Australia (Oceania)'],
            ['id' => 'GT', 'name' => 'Guatemala', 'continent' => 'North America'],
            ['id' => 'GG', 'name' => 'Guernsey', 'continent' => 'Europe'],
            ['id' => 'GN', 'name' => 'Guinea', 'continent' => 'Africa'],
            ['id' => 'GW', 'name' => 'Guinea-Bissau', 'continent' => 'Africa'],
            ['id' => 'GY', 'name' => 'Guyana', 'continent' => 'South America'],
            ['id' => 'HT', 'name' => 'Haiti', 'continent' => 'North America'],
            ['id' => 'HM', 'name' => 'Heard Island and Mcdonald Islands', 'continent' => 'Antarctica'],
            ['id' => 'HN', 'name' => 'Honduras', 'continent' => 'North America'],
            ['id' => 'HK', 'name' => 'Hong Kong', 'continent' => 'Asia'],
            ['id' => 'HU', 'name' => 'Hungary', 'continent' => 'Europe'],
            ['id' => 'IS', 'name' => 'Iceland', 'continent' => 'Europe'],
            ['id' => 'IN', 'name' => 'India', 'continent' => 'Asia'],
            ['id' => 'ID', 'name' => 'Indonesia', 'continent' => 'Asia'],
            ['id' => 'IR', 'name' => 'Iran', 'continent' => 'Asia'],
            ['id' => 'IQ', 'name' => 'Iraq', 'continent' => 'Asia'],
            ['id' => 'IE', 'name' => 'Ireland', 'continent' => 'Europe'],
            ['id' => 'IM', 'name' => 'Isle of Man', 'continent' => 'Europe'],
            ['id' => 'IL', 'name' => 'Israel', 'continent' => 'Asia'],
            ['id' => 'IT', 'name' => 'Italy', 'continent' => 'Europe'],
            ['id' => 'JM', 'name' => 'Jamaica', 'continent' => 'North America'],
            ['id' => 'JP', 'name' => 'Japan', 'continent' => 'Asia'],
            ['id' => 'JE', 'name' => 'Jersey', 'continent' => 'Europe'],
            ['id' => 'JO', 'name' => 'Jordan', 'continent' => 'Asia'],
            ['id' => 'KZ', 'name' => 'Kazakhstan', 'continent' => 'Asia'],
            ['id' => 'KE', 'name' => 'Kenya', 'continent' => 'Africa'],
            ['id' => 'KI', 'name' => 'Kiribati', 'continent' => 'Australia (Oceania)'],
            ['id' => 'KP', 'name' => 'Korea, North', 'continent' => 'Asia'],
            ['id' => 'KR', 'name' => 'Korea, South', 'continent' => 'Asia'],
            ['id' => 'XK', 'name' => 'Kosovo', 'continent' => 'Europe'],
            ['id' => 'KW', 'name' => 'Kuwait', 'continent' => 'Asia'],
            ['id' => 'KG', 'name' => 'Kyrgyzstan', 'continent' => 'Asia'],
            ['id' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'continent' => 'Asia'],
            ['id' => 'LV', 'name' => 'Latvia', 'continent' => 'Europe'],
            ['id' => 'LB', 'name' => 'Lebanon', 'continent' => 'Asia'],
            ['id' => 'LS', 'name' => 'Lesotho', 'continent' => 'Africa'],
            ['id' => 'LR', 'name' => 'Liberia', 'continent' => 'Africa'],
            ['id' => 'LY', 'name' => 'Libya', 'continent' => 'Africa'],
            ['id' => 'LI', 'name' => 'Liechtenstein', 'continent' => 'Europe'],
            ['id' => 'LT', 'name' => 'Lithuania', 'continent' => 'Europe'],
            ['id' => 'LU', 'name' => 'Luxembourg', 'continent' => 'Europe'],
            ['id' => 'MO', 'name' => 'Macao', 'continent' => 'Asia'],
            ['id' => 'MK', 'name' => 'Macedonia North', 'continent' => 'Europe'],
            ['id' => 'MG', 'name' => 'Madagascar', 'continent' => 'Africa'],
            ['id' => 'MW', 'name' => 'Malawi', 'continent' => 'Africa'],
            ['id' => 'MY', 'name' => 'Malaysia', 'continent' => 'Asia'],
            ['id' => 'MV', 'name' => 'Maldives', 'continent' => 'Asia'],
            ['id' => 'ML', 'name' => 'Mali', 'continent' => 'Africa'],
            ['id' => 'MT', 'name' => 'Malta', 'continent' => 'Europe'],
            ['id' => 'MH', 'name' => 'Marshall Islands', 'continent' => 'Australia (Oceania)'],
            ['id' => 'MQ', 'name' => 'Martinique', 'continent' => 'North America'],
            ['id' => 'MR', 'name' => 'Mauritania', 'continent' => 'Africa'],
            ['id' => 'MU', 'name' => 'Mauritius', 'continent' => 'Africa'],
            ['id' => 'YT', 'name' => 'Mayotte', 'continent' => 'Africa'],
            ['id' => 'MX', 'name' => 'Mexico', 'continent' => 'North America'],
            ['id' => 'FM', 'name' => 'Micronesia', 'continent' => 'Australia (Oceania)'],
            ['id' => 'MD', 'name' => 'Moldova', 'continent' => 'Europe'],
            ['id' => 'MC', 'name' => 'Monaco', 'continent' => 'Europe'],
            ['id' => 'MN', 'name' => 'Mongolia', 'continent' => 'Asia'],
            ['id' => 'ME', 'name' => 'Montenegro', 'continent' => 'Europe'],
            ['id' => 'MS', 'name' => 'Montserrat', 'continent' => 'North America'],
            ['id' => 'MA', 'name' => 'Morocco', 'continent' => 'Africa'],
            ['id' => 'MZ', 'name' => 'Mozambique', 'continent' => 'Africa'],
            ['id' => 'MM', 'name' => 'Myanmar (Burma)', 'continent' => 'Asia'],
            ['id' => 'NA', 'name' => 'Namibia', 'continent' => 'Africa'],
            ['id' => 'NR', 'name' => 'Nauru', 'continent' => 'Australia (Oceania)'],
            ['id' => 'NP', 'name' => 'Nepal', 'continent' => 'Asia'],
            ['id' => 'NL', 'name' => 'Netherlands', 'continent' => 'Europe'],
            ['id' => 'AN', 'name' => 'Netherlands Antilles', 'continent' => 'North America'],
            ['id' => 'NC', 'name' => 'New Caledonia', 'continent' => 'Australia (Oceania)'],
            ['id' => 'NZ', 'name' => 'New Zealand', 'continent' => 'Australia (Oceania)'],
            ['id' => 'NI', 'name' => 'Nicaragua', 'continent' => 'North America'],
            ['id' => 'NE', 'name' => 'Niger', 'continent' => 'Africa'],
            ['id' => 'NG', 'name' => 'Nigeria', 'continent' => 'Africa'],
            ['id' => 'NU', 'name' => 'Niue', 'continent' => 'Australia (Oceania)'],
            ['id' => 'NF', 'name' => 'Norfolk Island', 'continent' => 'Australia (Oceania)'],
            ['id' => 'MP', 'name' => 'Northern Mariana Islands', 'continent' => 'Australia (Oceania)'],
            ['id' => 'NO', 'name' => 'Norway', 'continent' => 'Europe'],
            ['id' => 'OM', 'name' => 'Oman', 'continent' => 'Asia'],
            ['id' => 'PK', 'name' => 'Pakistan', 'continent' => 'Asia'],
            ['id' => 'PW', 'name' => 'Palau', 'continent' => 'Australia (Oceania)'],
            ['id' => 'PS', 'name' => 'Palestine', 'continent' => 'Asia'],
            ['id' => 'PA', 'name' => 'Panama', 'continent' => 'North America'],
            ['id' => 'PG', 'name' => 'Papua New Guinea', 'continent' => 'Australia (Oceania)'],
            ['id' => 'PY', 'name' => 'Paraguay', 'continent' => 'South America'],
            ['id' => 'PE', 'name' => 'Peru', 'continent' => 'South America'],
            ['id' => 'PH', 'name' => 'Philippines', 'continent' => 'Asia'],
            ['id' => 'PN', 'name' => 'Pitcairn Islands', 'continent' => 'Australia (Oceania)'],
            ['id' => 'PL', 'name' => 'Poland', 'continent' => 'Europe'],
            ['id' => 'PT', 'name' => 'Portugal', 'continent' => 'Europe'],
            ['id' => 'PR', 'name' => 'Puerto Rico', 'continent' => 'North America'],
            ['id' => 'QA', 'name' => 'Qatar', 'continent' => 'Asia'],
            ['id' => 'RE', 'name' => 'Reunion', 'continent' => 'Africa'],
            ['id' => 'RO', 'name' => 'Romania', 'continent' => 'Europe'],
            ['id' => 'RU', 'name' => 'Russian Federation', 'continent' => 'Asia'],
            ['id' => 'RW', 'name' => 'Rwanda', 'continent' => 'Africa'],
            ['id' => 'BL', 'name' => 'Saint Barthelemy', 'continent' => 'North America'],
            ['id' => 'SH', 'name' => 'Saint Helena', 'continent' => 'Africa'],
            ['id' => 'KN', 'name' => 'Saint Kitts and Nevis', 'continent' => 'North America'],
            ['id' => 'LC', 'name' => 'Saint Lucia', 'continent' => 'North America'],
            ['id' => 'MF', 'name' => 'Saint Martin', 'continent' => 'North America'],
            ['id' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'continent' => 'North America'],
            ['id' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'continent' => 'North America'],
            ['id' => 'WS', 'name' => 'Samoa', 'continent' => 'Australia (Oceania)'],
            ['id' => 'SM', 'name' => 'San Marino', 'continent' => 'Europe'],
            ['id' => 'ST', 'name' => 'Sao Tome and Principe', 'continent' => 'Africa'],
            ['id' => 'SA', 'name' => 'Saudi Arabia', 'continent' => 'Asia'],
            ['id' => 'SN', 'name' => 'Senegal', 'continent' => 'Africa'],
            ['id' => 'RS', 'name' => 'Serbia', 'continent' => 'Europe'],
            ['id' => 'CS', 'name' => 'Serbia and Montenegro', 'continent' => 'Europe'],
            ['id' => 'SC', 'name' => 'Seychelles', 'continent' => 'Africa'],
            ['id' => 'SL', 'name' => 'Sierra Leone', 'continent' => 'Africa'],
            ['id' => 'SG', 'name' => 'Singapore', 'continent' => 'Asia'],
            ['id' => 'SX', 'name' => 'Sint Maarten', 'continent' => 'North America'],
            ['id' => 'SK', 'name' => 'Slovakia', 'continent' => 'Europe'],
            ['id' => 'SI', 'name' => 'Slovenia', 'continent' => 'Europe'],
            ['id' => 'SB', 'name' => 'Solomon Islands', 'continent' => 'Australia (Oceania)'],
            ['id' => 'SO', 'name' => 'Somalia', 'continent' => 'Africa'],
            ['id' => 'ZA', 'name' => 'South Africa', 'continent' => 'Africa'],
            ['id' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'continent' => 'Antarctica'],
            ['id' => 'SS', 'name' => 'South Sudan', 'continent' => 'Africa'],
            ['id' => 'ES', 'name' => 'Spain', 'continent' => 'Europe'],
            ['id' => 'LK', 'name' => 'Sri Lanka', 'continent' => 'Asia'],
            ['id' => 'SD', 'name' => 'Sudan', 'continent' => 'Africa'],
            ['id' => 'SR', 'name' => 'Suriname', 'continent' => 'South America'],
            ['id' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'continent' => 'Europe'],
            ['id' => 'SE', 'name' => 'Sweden', 'continent' => 'Europe'],
            ['id' => 'CH', 'name' => 'Switzerland', 'continent' => 'Europe'],
            ['id' => 'SY', 'name' => 'Syria', 'continent' => 'Asia'],
            ['id' => 'TW', 'name' => 'Taiwan', 'continent' => 'Asia'],
            ['id' => 'TJ', 'name' => 'Tajikistan', 'continent' => 'Asia'],
            ['id' => 'TZ', 'name' => 'Tanzania', 'continent' => 'Africa'],
            ['id' => 'TH', 'name' => 'Thailand', 'continent' => 'Asia'],
            ['id' => 'TL', 'name' => 'Timor-Leste', 'continent' => 'Asia'],
            ['id' => 'TG', 'name' => 'Togo', 'continent' => 'Africa'],
            ['id' => 'TK', 'name' => 'Tokelau', 'continent' => 'Australia (Oceania)'],
            ['id' => 'TO', 'name' => 'Tonga', 'continent' => 'Australia (Oceania)'],
            ['id' => 'TT', 'name' => 'Trinidad and Tobago', 'continent' => 'North America'],
            ['id' => 'TN', 'name' => 'Tunisia', 'continent' => 'Africa'],
            ['id' => 'TR', 'name' => 'Turkey (Türkiye)', 'continent' => 'Asia'],
            ['id' => 'TM', 'name' => 'Turkmenistan', 'continent' => 'Asia'],
            ['id' => 'TC', 'name' => 'Turks and Caicos Islands', 'continent' => 'North America'],
            ['id' => 'TV', 'name' => 'Tuvalu', 'continent' => 'Australia (Oceania)'],
            ['id' => 'UM', 'name' => 'U.S. Outlying Islands', 'continent' => 'North America'],
            ['id' => 'UG', 'name' => 'Uganda', 'continent' => 'Africa'],
            ['id' => 'UA', 'name' => 'Ukraine', 'continent' => 'Europe'],
            ['id' => 'AE', 'name' => 'United Arab Emirates', 'continent' => 'Asia'],
            ['id' => 'GB', 'name' => 'United Kingdom', 'continent' => 'Europe'],
            ['id' => 'US', 'name' => 'United States', 'continent' => 'North America'],
            ['id' => 'UY', 'name' => 'Uruguay', 'continent' => 'South America'],
            ['id' => 'UZ', 'name' => 'Uzbekistan', 'continent' => 'Asia'],
            ['id' => 'VU', 'name' => 'Vanuatu', 'continent' => 'Australia (Oceania)'],
            ['id' => 'VA', 'name' => 'Vatican City Holy See', 'continent' => 'Europe'],
            ['id' => 'VE', 'name' => 'Venezuela', 'continent' => 'South America'],
            ['id' => 'VN', 'name' => 'Vietnam', 'continent' => 'Asia'],
            ['id' => 'VG', 'name' => 'Virgin Islands, British', 'continent' => 'North America'],
            ['id' => 'VI', 'name' => 'Virgin Islands, U.S', 'continent' => 'North America'],
            ['id' => 'WF', 'name' => 'Wallis and Futuna', 'continent' => 'Australia (Oceania)'],
            ['id' => 'EH', 'name' => 'Western Sahara', 'continent' => 'Africa'],
            ['id' => 'YE', 'name' => 'Yemen', 'continent' => 'Asia'],
            ['id' => 'ZM', 'name' => 'Zambia', 'continent' => 'Africa'],
            ['id' => 'ZW', 'name' => 'Zimbabwe', 'continent' => 'Africa'],
        ];

        Region::insert($region);
    }
}
